# Generated by Django 3.2.12 on 2022-06-06 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=1, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('team', models.CharField(max_length=50)),
                ('noc', models.CharField(max_length=3)),
                ('games', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('sport', models.CharField(max_length=20)),
                ('event', models.CharField(max_length=20)),
                ('medal', models.CharField(max_length=20)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Athlete',
                'verbose_name_plural': 'Athletes',
                'unique_together': {('name', 'age')},
            },
        ),
    ]
